controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_prismatic_joint_1
      - gripper_prismatic_joint_2
initial:  # Define initial robot poses per group
  - group: arm
    pose: rest_arm
  - group: gripper
    pose: closed_gripper