arm_controller:
  follow_joint_trajectory:
    type: "robot_controllers/FollowJointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  gravity_compensation:
    type: "robot_controllers/GravityCompensation"
    root: "joint_1"
    tip: "joint_5"
    autostart: true

gripper_controller:
  gripper_action:
    type: "robot_controllers/ParallelGripperController"
    centering:
      p: 1000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0

gazebo:
  default_controllers:
    - "arm_controller/follow_joint_trajectory"
    - "arm_controller/gravity_compensation"
    - "gripper_controller/gripper_action"
  joint_1:
    position:
      p: 100.0
      d: 0.1
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 10.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  joint_2:
    position:
      p: 100.0
      d: 0.1
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 150.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  joint_3:
    position:
      p: 100.0
      d: 0.1
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 150.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  joint_4:
    position:
      p: 100.0
      d: 0.1
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 100.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  joint_5:
    position:
      p: 100.0
      d: 0.1
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 100.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  gripper_prismatic_joint_1:
    position:
      p: 5000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  gripper_prismatic_joint_2:
    position:
      p: 5000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0


controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: gripper_controller
    type: GripperCommand
    action_ns: gripper_action
    default: true
    parallel: true
    joints:
      - gripper_prismatic_joint_1
      - gripper_prismatic_joint_2
