# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
  gains:
    joint_1:
      p: 100
      d: 0.01
      i: 10
      i_clamp: 1
    joint_2:
      p: 100
      d: 0.01
      i: 10
      i_clamp: 1
    joint_3:
      p: 100
      d: 0.01
      i: 10
      i_clamp: 1
    joint_4:
      p: 100
      d: 0.01
      i: 10
      i_clamp: 1
    joint_5:
      p: 100
      d: 0.01
      i: 10
      i_clamp: 1

  # constraints:
  #   joint_1:
  #     goal: 1.0
  #     trajectory: 1.0
  #   joint_2:
  #     goal: 1.0
  #     trajectory: 1.0
  #   joint_3:
  #     goal: 1.0
  #     trajectory: 1.0
  #   joint_4:
  #     goal: 1.0
  #     trajectory: 1.0
  #   joint_5:
  #     goal: 1.0
  #     trajectory: 1.0

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_prismatic_joint_1
    - gripper_prismatic_joint_2
  gains:
    gripper_prismatic_joint_1:
      p: 100
      d: 0.01
      i: 10
      i_clamp: 1
    gripper_prismatic_joint_2:
      p: 100
      d: 0.01
      i: 10
      i_clamp: 1
